include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: warning
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.mocks.dart'
    - 'build/**'
    - 'lib/generated/**'

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_print
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - prefer_const_constructors
    - prefer_final_locals
    - unawaited_futures
